version: '3.1'

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:12.1
    secrets:
      - psql-passwd
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-passwd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql-passwd:
    file: ./psql-passwd.txt      # this means docker stack WILL create the secrets for us as long as the specific secret file exists. We DONOT need to manually create secrets

